# -*- coding: utf-8 -*-
"""avareageYears.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yZDXzOEgQuZbNTPm6soSTLxpm15c_w6_
"""

def avareageYears(datalistYear,datalistMonth):
  """
    This function evaluates the avarage of year and month of a list.
    Inputs:
    datalistYear = The list with the years.
    datalistMonth = The list with the monts.
    Outputs:
    anomedia = The avarage year.
    mesmedia = The avarage mont.
  """
  if [type(datalistYear),type(datalistMonth)] == [list,list]:
    L = len(datalistYear)
    if L == len(datalistMonth):
      anomes = 0
      for i in range(L):
        anomes += datalistYear[i] * 12 + datalistMonth[i]
      media = anomes/ L
      anomedia = int(media/12)
      mesmedia = (media%12)
      print('Avarege = {} years and {:.2f} months.'.format(anomedia,mesmedia))  
    else:
      print('Lists should have the same size')  
      print('Size of year = {}, size of month = {}'.format(L, len(datalistMonth)))
      return
  else:
    print('Data should be in python list format.')
    return
  return anomedia, mesmedia

